[package]
name = "clamav-client"
version = "0.3.3"
authors = ["Thorsten Blum <thorsten.blum@toblux.com>"]
edition = "2021"
homepage = "https://github.com/toblux/rust-clamav-client"
repository = "https://github.com/toblux/rust-clamav-client"
description = "ClamAV client library with optional Tokio support"
readme = "README.md"
license = "MIT"
keywords = ["clamav", "clamd", "anitvirus", "async", "tokio"]

[dependencies]
tokio = { version = "1.34.0", features = ["fs", "io-util", "net"], optional = true }
tokio-stream = { version = "0.1.14", optional = true }
bytes = { version = "1", optional = true }

[dev-dependencies]
tokio = { version = "1.34.0", features = ["io-std", "macros", "rt"] }
tokio-util = { version = "0.7.10", features = ["io"] }

[features]
tokio = ["dep:tokio"]
tokio-stream = ["tokio", "dep:tokio-stream", "dep:bytes"]

[package.metadata.docs.rs]
features = ["tokio", "tokio-stream"]
