name: Run tests
on: [push, pull_request]

jobs:
  test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install ClamAV daemon
        run: sudo apt-get install clamav-daemon
      - name: Start clamd
        run: clamd --config-file=tests/clamav/clamd.conf --datadir=tests/clamav/database/
      - name: Run tests
        run: cargo test --all-features -- --skip oversized
      - name: Shutdown clamd
        run: echo SHUTDOWN | nc localhost 3310
  test_windows:
    env:
      CLAMAV_WIN_VERSION: clamav-1.0.4.win.x64
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install ClamAV
        run: |
          curl -L -o clamav.zip https://www.clamav.net/downloads/production/${{ env.CLAMAV_WIN_VERSION }}.zip
          tar -xf clamav.zip
      - name: Start clamd
        run: |
          cp -r tests\clamav\database ${{ env.CLAMAV_WIN_VERSION }}
          cp tests\clamav\clamd.conf ${{ env.CLAMAV_WIN_VERSION }}
          ${{ env.CLAMAV_WIN_VERSION }}\clamd.exe --install-service
          net start clamd
      - name: Run tests
        run: cargo test --all-features -- --skip oversized
      - name: Shutdown clamd
        run: |
          net stop clamd
          ${{ env.CLAMAV_WIN_VERSION }}\clamd.exe --uninstall-service
