name: Run tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install cargo binstall
        uses: cargo-bins/cargo-binstall@main
      - name: Verify MSRV
        run: |
          cargo binstall --version 0.17.1 --no-confirm cargo-msrv
          cargo msrv verify
      - name: Start ClamAV daemon
        uses: toblux/start-clamd-github-action@v0.2
        with:
          stream_max_length: 1000000
      - name: Run tests with separate features
        run: |
          cargo test --features tokio
          cargo test --features tokio-stream
          cargo test --features async-std
      - name: Run tests with all features
        run: cargo test --all-features
